### ISSUE TITLE
Up to date with standalone Desmume?

### ISSUE THREAD

**Issue by BParks21** [libretro/desmume2015#121]
Sorry, i just want to know if we can get this port up to date with the latest Desmume features? That way we can play Pokemon with no black dots.

**Comment by Enverex** [comment]
If the commits read correctly, this is currently a fork from August 6th, 2015? Just to put a timestamp on it.

**Comment by bearoso** [comment]
I've done a rebase of the libretro core on upstream Desmume here: https://github.com/bearoso/desmume

Much of the emulator core was torn to shreds in the libretro repository, so I had to start fresh. My goal was getting the OpenGL renderer working, since it has better compatibility in the games I'm interested in running. 

ATM, it's working perfectly on Linux with a spurious glib dependency that's minor to get rid of. I tried to keep the core close to intact so it can be updated easier. OpenGL mode needs a compatibility context because I used immediate mode for the final upload in my rush. Desmume GL rendering code isn't GLES-compatible. No idea how it builds or runs on Windows.

**Comment by andres-asm** [comment]
Thank you for the new port!

**Comment by BParks21** [comment]
Wait so how do i download this new port and test it?

**Comment by bearoso** [comment]
If you've got Linux or BSD, clone the repo, head to the desmume/src/frontend/libretro directory, and type "make". Copy the libretro_desmume.so library to your ~/.config/retroarch/cores directory.

I don't have Windows. So if you have that you'll have to have someone try and build it.

I know there's still a few things I want to improve.

**Comment by BParks21** [comment]
Dang i have windows and don't know how to do it and don't know anyone personally who can. Will this be released for retroarch officially?

**Comment by hizzlekizzle** [comment]
Yes, whenever it's ready for general consumption, we'll probably twilight the old one and switch over to this one.

**Comment by bearoso** [comment]
I'm working on building it for Windows now. I'll see what I can do.

**Comment by bearoso** [comment]
Building and running fine on Windows with mingw now, or at least the 64-bit version, 
I'm having trouble building a 32-bit version because of my makeshift Windows environment.

dll here: 
https://sites.google.com/site/bearoso/misc/desmume_libretro.zip

Unzip and pop it into your retroarch cores directory.

**Comment by BParks21** [comment]
Wow thank you very much

**Comment by bearoso** [comment]
I've updated the dll with the save file and crash fixes.

**Comment by andres-asm** [comment]
Works really well except for the fact that it doesn't work with most glsl shaders if the shader was preset at startup which is something that has never happened before

If you load the shader while in-game it works but if you keep cycling shaders you end up with a black screen

That said:
![image](https://user-images.githubusercontent.com/1721040/36627160-c218b20e-190c-11e8-9009-1a92e6407ccf.png)

I don't think the old core was even close to 60fps at this internal res.

**Comment by andres-asm** [comment]
I still have some crashes on load state tho. Also screenshots are totally black. (RetroArch Screenshots)

**Comment by BParks21** [comment]
Also have all the mentioned issues, especially loading shaders. Other than that it's amazing! I hated using standalone demume because it has serious frame pacing problems.

**Comment by bearoso** [comment]
Haven't messed with save states a lot because I generally don't use them. Same with shaders other than my usual standbys. I'll look into these things.

**Comment by Awakened0** [comment]
The microphone toggle doesn't seem to be working with the same settings I was using with the old core. I tried toggling "Force Microphone Enable" and the different "Microphone Simulation" settings but nothing worked with Super Princess Peach. With the old core "off" and "internal" worked. You can test it by loading this save, going to 5-2 and running through the level up till you go into a pipe and end up in a sub. Toggling the mic should make the sub shoot bubbles.

[SPP Save.zip](https://github.com/libretro/desmume2015/files/1755194/SPP.Save.zip)

**Comment by BParks21** [comment]
I'm also experiencing a crash when switching cpu modes in the core options and resuming the game. Always results in a crash. Is this normal? Works fine if I switch then close the game and relaunch it.

**Comment by bearoso** [comment]
> I'm also experiencing a crash when switching cpu modes in the core options and resuming the game. Always results in a crash. Is this normal? Works fine if I switch then close the game and relaunch it.

I'm not sure you should be doing that, really. I mean, it might work sometimes, which is probably why it's not a relaunch-only option, but I don't think it's a good idea. 

Also, there's a new desmume repository up, so you can file any specific issues there.
