### ISSUE TITLE
Fake mic noise support

### ISSUE THREAD

**Issue by Oggom** [libretro/desmume2015#8]
Desmume has an option to play a fake microphone noise even when there's no physical mic available.
I think it would be helpful to have it available in the libretro port too since certain games cannot be finished without using a mic.

**Comment by Awakened0** [comment]
I had to copy my save over to stand alone Desmume near the end of Ace Attorney Investigations 2 because they threw in one of those finger print blowing things out of the blue :/. Super Princess Peach has submarine sections where you blow on the mic to shoot bubbles, but I've been able to get through those without needing to do that so far.

**Comment by Oggom** [comment]
Added by https://github.com/libretro/desmume/pull/27
